library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_ARITH.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;

--use work.array_def.all;

package array_def is

type std_logic_bit2  is array (natural range <>) of std_logic_vector(1  downto 0);
type std_logic_bit3  is array (natural range <>) of std_logic_vector(2  downto 0);
type std_logic_bit4  is array (natural range <>) of std_logic_vector(3  downto 0);
type std_logic_bit5  is array (natural range <>) of std_logic_vector(4  downto 0);
type std_logic_bit6  is array (natural range <>) of std_logic_vector(5  downto 0);
type std_logic_bit7  is array (natural range <>) of std_logic_vector(6  downto 0);
type std_logic_bit8  is array (natural range <>) of std_logic_vector(7  downto 0);
type std_logic_bit9  is array (natural range <>) of std_logic_vector(8  downto 0);
type std_logic_bit10 is array (natural range <>) of std_logic_vector(9  downto 0);
type std_logic_bit11 is array (natural range <>) of std_logic_vector(10 downto 0);
type std_logic_bit12 is array (natural range <>) of std_logic_vector(11 downto 0);
type std_logic_bit13 is array (natural range <>) of std_logic_vector(12 downto 0);
type std_logic_bit14 is array (natural range <>) of std_logic_vector(13 downto 0);
type std_logic_bit15 is array (natural range <>) of std_logic_vector(14 downto 0);
type std_logic_bit16 is array (natural range <>) of std_logic_vector(15 downto 0);
type std_logic_bit17 is array (natural range <>) of std_logic_vector(16 downto 0);
type std_logic_bit18 is array (natural range <>) of std_logic_vector(17 downto 0);
type std_logic_bit19 is array (natural range <>) of std_logic_vector(18 downto 0);
type std_logic_bit20 is array (natural range <>) of std_logic_vector(19 downto 0);
type std_logic_bit21 is array (natural range <>) of std_logic_vector(20 downto 0);
type std_logic_bit22 is array (natural range <>) of std_logic_vector(21 downto 0);
type std_logic_bit23 is array (natural range <>) of std_logic_vector(22 downto 0);
type std_logic_bit24 is array (natural range <>) of std_logic_vector(23 downto 0);
type std_logic_bit25 is array (natural range <>) of std_logic_vector(24 downto 0);
type std_logic_bit26 is array (natural range <>) of std_logic_vector(25 downto 0);
type std_logic_bit27 is array (natural range <>) of std_logic_vector(26 downto 0);
type std_logic_bit28 is array (natural range <>) of std_logic_vector(27 downto 0);
type std_logic_bit29 is array (natural range <>) of std_logic_vector(28 downto 0);
type std_logic_bit30 is array (natural range <>) of std_logic_vector(29 downto 0);
type std_logic_bit31 is array (natural range <>) of std_logic_vector(30 downto 0);
type std_logic_bit32 is array (natural range <>) of std_logic_vector(31 downto 0);
type std_logic_bit33 is array (natural range <>) of std_logic_vector(32 downto 0);
type std_logic_bit34 is array (natural range <>) of std_logic_vector(33 downto 0);
type std_logic_bit35 is array (natural range <>) of std_logic_vector(34 downto 0);
type std_logic_bit36 is array (natural range <>) of std_logic_vector(35 downto 0);
type std_logic_bit37 is array (natural range <>) of std_logic_vector(36 downto 0);
type std_logic_bit38 is array (natural range <>) of std_logic_vector(37 downto 0);
type std_logic_bit39 is array (natural range <>) of std_logic_vector(38 downto 0);
type std_logic_bit40 is array (natural range <>) of std_logic_vector(39 downto 0);
type std_logic_bit41 is array (natural range <>) of std_logic_vector(40 downto 0);
type std_logic_bit42 is array (natural range <>) of std_logic_vector(41 downto 0);
type std_logic_bit43 is array (natural range <>) of std_logic_vector(42 downto 0);
type std_logic_bit44 is array (natural range <>) of std_logic_vector(43 downto 0);
type std_logic_bit45 is array (natural range <>) of std_logic_vector(44 downto 0);
type std_logic_bit46 is array (natural range <>) of std_logic_vector(45 downto 0);
type std_logic_bit47 is array (natural range <>) of std_logic_vector(46 downto 0);
type std_logic_bit48 is array (natural range <>) of std_logic_vector(47 downto 0);
type std_logic_bit49 is array (natural range <>) of std_logic_vector(48 downto 0);
type std_logic_bit50 is array (natural range <>) of std_logic_vector(49 downto 0);
type std_logic_bit51 is array (natural range <>) of std_logic_vector(50 downto 0);
type std_logic_bit52 is array (natural range <>) of std_logic_vector(51 downto 0);
type std_logic_bit53 is array (natural range <>) of std_logic_vector(52 downto 0);
type std_logic_bit54 is array (natural range <>) of std_logic_vector(53 downto 0);
type std_logic_bit55 is array (natural range <>) of std_logic_vector(54 downto 0);
type std_logic_bit56 is array (natural range <>) of std_logic_vector(55 downto 0);
type std_logic_bit57 is array (natural range <>) of std_logic_vector(56 downto 0);
type std_logic_bit58 is array (natural range <>) of std_logic_vector(57 downto 0);
type std_logic_bit59 is array (natural range <>) of std_logic_vector(58 downto 0);
type std_logic_bit60 is array (natural range <>) of std_logic_vector(59 downto 0);
type std_logic_bit61 is array (natural range <>) of std_logic_vector(60 downto 0);
type std_logic_bit62 is array (natural range <>) of std_logic_vector(61 downto 0);
type std_logic_bit63 is array (natural range <>) of std_logic_vector(62 downto 0);
type std_logic_bit64 is array (natural range <>) of std_logic_vector(63 downto 0);

end;
